---
galaxy_info:
  author: "Elizabeth Ogundepo"
  license: "Proprietary"
  role_name: hcloud_server
  description: Creates a Hetzner Cloud server and pre-attaches floating egress IPs
  min_ansible_version: "2.15"

dependencies: []
