---
- name: Install WireGuard (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ wireguard_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Ensure wireguard config directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  when: wireguard_enable_ip_forward | bool

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  when:
    - wireguard_enable_ip_forward | bool
    - wireguard_enable_ipv6 | bool
